// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package testproto is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	TestUint
	TestInt
	TestBool
	TestBytes
	TestSlice
*/
package testproto

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type TestUint struct {
	Uint32           *uint32 `protobuf:"varint,1,req" json:"Uint32,omitempty"`
	Uint64           *uint64 `protobuf:"varint,2,req" json:"Uint64,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TestUint) Reset()         { *m = TestUint{} }
func (m *TestUint) String() string { return proto.CompactTextString(m) }
func (*TestUint) ProtoMessage()    {}

func (m *TestUint) GetUint32() uint32 {
	if m != nil && m.Uint32 != nil {
		return *m.Uint32
	}
	return 0
}

func (m *TestUint) GetUint64() uint64 {
	if m != nil && m.Uint64 != nil {
		return *m.Uint64
	}
	return 0
}

type TestInt struct {
	Int32            *int32 `protobuf:"varint,1,req" json:"Int32,omitempty"`
	Int64            *int64 `protobuf:"varint,2,req" json:"Int64,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TestInt) Reset()         { *m = TestInt{} }
func (m *TestInt) String() string { return proto.CompactTextString(m) }
func (*TestInt) ProtoMessage()    {}

func (m *TestInt) GetInt32() int32 {
	if m != nil && m.Int32 != nil {
		return *m.Int32
	}
	return 0
}

func (m *TestInt) GetInt64() int64 {
	if m != nil && m.Int64 != nil {
		return *m.Int64
	}
	return 0
}

type TestBool struct {
	Bool             *bool  `protobuf:"varint,1,req" json:"Bool,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TestBool) Reset()         { *m = TestBool{} }
func (m *TestBool) String() string { return proto.CompactTextString(m) }
func (*TestBool) ProtoMessage()    {}

func (m *TestBool) GetBool() bool {
	if m != nil && m.Bool != nil {
		return *m.Bool
	}
	return false
}

type TestBytes struct {
	String_          *string `protobuf:"bytes,1,req" json:"String,omitempty"`
	Bytes            []byte  `protobuf:"bytes,2,req" json:"Bytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TestBytes) Reset()         { *m = TestBytes{} }
func (m *TestBytes) String() string { return proto.CompactTextString(m) }
func (*TestBytes) ProtoMessage()    {}

func (m *TestBytes) GetString_() string {
	if m != nil && m.String_ != nil {
		return *m.String_
	}
	return ""
}

func (m *TestBytes) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

type TestSlice struct {
	Uint32Slice      []uint32 `protobuf:"varint,1,rep,packed" json:"Uint32Slice,omitempty"`
	Uint64Slice      []uint64 `protobuf:"varint,2,rep,packed" json:"Uint64Slice,omitempty"`
	Int32Slice       []int32  `protobuf:"varint,3,rep,packed" json:"Int32Slice,omitempty"`
	Int64Slice       []int64  `protobuf:"varint,4,rep,packed" json:"Int64Slice,omitempty"`
	BoolSlice        []bool   `protobuf:"varint,5,rep,packed" json:"BoolSlice,omitempty"`
	StringSlice      []string `protobuf:"bytes,6,rep" json:"StringSlice,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *TestSlice) Reset()         { *m = TestSlice{} }
func (m *TestSlice) String() string { return proto.CompactTextString(m) }
func (*TestSlice) ProtoMessage()    {}

func (m *TestSlice) GetUint32Slice() []uint32 {
	if m != nil {
		return m.Uint32Slice
	}
	return nil
}

func (m *TestSlice) GetUint64Slice() []uint64 {
	if m != nil {
		return m.Uint64Slice
	}
	return nil
}

func (m *TestSlice) GetInt32Slice() []int32 {
	if m != nil {
		return m.Int32Slice
	}
	return nil
}

func (m *TestSlice) GetInt64Slice() []int64 {
	if m != nil {
		return m.Int64Slice
	}
	return nil
}

func (m *TestSlice) GetBoolSlice() []bool {
	if m != nil {
		return m.BoolSlice
	}
	return nil
}

func (m *TestSlice) GetStringSlice() []string {
	if m != nil {
		return m.StringSlice
	}
	return nil
}

func init() {
}
