// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package testproto is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	ProtoTypes
	ProtoSlice
	ProtoBytes
	ProtoStruct
	ProtoTags
	ProtoTagsSlice
*/
package testproto

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ProtoTypes struct {
	Uint32           *uint32  `protobuf:"varint,1,req" json:"Uint32,omitempty"`
	Uint64           *uint64  `protobuf:"varint,2,req" json:"Uint64,omitempty"`
	Int32            *int32   `protobuf:"varint,3,req" json:"Int32,omitempty"`
	Int64            *int64   `protobuf:"varint,4,req" json:"Int64,omitempty"`
	Float32          *float32 `protobuf:"fixed32,5,req" json:"Float32,omitempty"`
	Float64          *float64 `protobuf:"fixed64,6,req" json:"Float64,omitempty"`
	Bool             *bool    `protobuf:"varint,7,req" json:"Bool,omitempty"`
	String_          *string  `protobuf:"bytes,8,req" json:"String,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoTypes) Reset()         { *m = ProtoTypes{} }
func (m *ProtoTypes) String() string { return proto.CompactTextString(m) }
func (*ProtoTypes) ProtoMessage()    {}

func (m *ProtoTypes) GetUint32() uint32 {
	if m != nil && m.Uint32 != nil {
		return *m.Uint32
	}
	return 0
}

func (m *ProtoTypes) GetUint64() uint64 {
	if m != nil && m.Uint64 != nil {
		return *m.Uint64
	}
	return 0
}

func (m *ProtoTypes) GetInt32() int32 {
	if m != nil && m.Int32 != nil {
		return *m.Int32
	}
	return 0
}

func (m *ProtoTypes) GetInt64() int64 {
	if m != nil && m.Int64 != nil {
		return *m.Int64
	}
	return 0
}

func (m *ProtoTypes) GetFloat32() float32 {
	if m != nil && m.Float32 != nil {
		return *m.Float32
	}
	return 0
}

func (m *ProtoTypes) GetFloat64() float64 {
	if m != nil && m.Float64 != nil {
		return *m.Float64
	}
	return 0
}

func (m *ProtoTypes) GetBool() bool {
	if m != nil && m.Bool != nil {
		return *m.Bool
	}
	return false
}

func (m *ProtoTypes) GetString_() string {
	if m != nil && m.String_ != nil {
		return *m.String_
	}
	return ""
}

type ProtoSlice struct {
	Uint32Slice      []uint32  `protobuf:"varint,1,rep" json:"Uint32Slice,omitempty"`
	Uint64Slice      []uint64  `protobuf:"varint,2,rep" json:"Uint64Slice,omitempty"`
	Int32Slice       []int32   `protobuf:"varint,3,rep" json:"Int32Slice,omitempty"`
	Int64Slice       []int64   `protobuf:"varint,4,rep" json:"Int64Slice,omitempty"`
	Float32Slice     []float32 `protobuf:"fixed32,5,rep" json:"Float32Slice,omitempty"`
	Float64Slice     []float64 `protobuf:"fixed64,6,rep" json:"Float64Slice,omitempty"`
	BoolSlice        []bool    `protobuf:"varint,7,rep" json:"BoolSlice,omitempty"`
	StringSlice      []string  `protobuf:"bytes,8,rep" json:"StringSlice,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ProtoSlice) Reset()         { *m = ProtoSlice{} }
func (m *ProtoSlice) String() string { return proto.CompactTextString(m) }
func (*ProtoSlice) ProtoMessage()    {}

func (m *ProtoSlice) GetUint32Slice() []uint32 {
	if m != nil {
		return m.Uint32Slice
	}
	return nil
}

func (m *ProtoSlice) GetUint64Slice() []uint64 {
	if m != nil {
		return m.Uint64Slice
	}
	return nil
}

func (m *ProtoSlice) GetInt32Slice() []int32 {
	if m != nil {
		return m.Int32Slice
	}
	return nil
}

func (m *ProtoSlice) GetInt64Slice() []int64 {
	if m != nil {
		return m.Int64Slice
	}
	return nil
}

func (m *ProtoSlice) GetFloat32Slice() []float32 {
	if m != nil {
		return m.Float32Slice
	}
	return nil
}

func (m *ProtoSlice) GetFloat64Slice() []float64 {
	if m != nil {
		return m.Float64Slice
	}
	return nil
}

func (m *ProtoSlice) GetBoolSlice() []bool {
	if m != nil {
		return m.BoolSlice
	}
	return nil
}

func (m *ProtoSlice) GetStringSlice() []string {
	if m != nil {
		return m.StringSlice
	}
	return nil
}

type ProtoBytes struct {
	Bytes            []byte   `protobuf:"bytes,1,req" json:"Bytes,omitempty"`
	BytesSlice       [][]byte `protobuf:"bytes,2,rep" json:"BytesSlice,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoBytes) Reset()         { *m = ProtoBytes{} }
func (m *ProtoBytes) String() string { return proto.CompactTextString(m) }
func (*ProtoBytes) ProtoMessage()    {}

func (m *ProtoBytes) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *ProtoBytes) GetBytesSlice() [][]byte {
	if m != nil {
		return m.BytesSlice
	}
	return nil
}

type ProtoStruct struct {
	Struct1          *ProtoStruct_Struct `protobuf:"bytes,1,req" json:"Struct1,omitempty"`
	Struct2          *ProtoStruct_Struct `protobuf:"bytes,2,req" json:"Struct2,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoStruct) Reset()         { *m = ProtoStruct{} }
func (m *ProtoStruct) String() string { return proto.CompactTextString(m) }
func (*ProtoStruct) ProtoMessage()    {}

func (m *ProtoStruct) GetStruct1() *ProtoStruct_Struct {
	if m != nil {
		return m.Struct1
	}
	return nil
}

func (m *ProtoStruct) GetStruct2() *ProtoStruct_Struct {
	if m != nil {
		return m.Struct2
	}
	return nil
}

type ProtoStruct_Struct struct {
	Uint32           *uint32 `protobuf:"varint,1,req" json:"Uint32,omitempty"`
	Uint64           *uint64 `protobuf:"varint,2,req" json:"Uint64,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoStruct_Struct) Reset()         { *m = ProtoStruct_Struct{} }
func (m *ProtoStruct_Struct) String() string { return proto.CompactTextString(m) }
func (*ProtoStruct_Struct) ProtoMessage()    {}

func (m *ProtoStruct_Struct) GetUint32() uint32 {
	if m != nil && m.Uint32 != nil {
		return *m.Uint32
	}
	return 0
}

func (m *ProtoStruct_Struct) GetUint64() uint64 {
	if m != nil && m.Uint64 != nil {
		return *m.Uint64
	}
	return 0
}

type ProtoTags struct {
	Sfixed32         *int32  `protobuf:"fixed32,1,req" json:"Sfixed32,omitempty"`
	Sfixed64         *int64  `protobuf:"fixed64,2,req" json:"Sfixed64,omitempty"`
	Fixed32          *uint32 `protobuf:"fixed32,3,req" json:"Fixed32,omitempty"`
	Fixed64          *uint64 `protobuf:"fixed64,4,req" json:"Fixed64,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoTags) Reset()         { *m = ProtoTags{} }
func (m *ProtoTags) String() string { return proto.CompactTextString(m) }
func (*ProtoTags) ProtoMessage()    {}

func (m *ProtoTags) GetSfixed32() int32 {
	if m != nil && m.Sfixed32 != nil {
		return *m.Sfixed32
	}
	return 0
}

func (m *ProtoTags) GetSfixed64() int64 {
	if m != nil && m.Sfixed64 != nil {
		return *m.Sfixed64
	}
	return 0
}

func (m *ProtoTags) GetFixed32() uint32 {
	if m != nil && m.Fixed32 != nil {
		return *m.Fixed32
	}
	return 0
}

func (m *ProtoTags) GetFixed64() uint64 {
	if m != nil && m.Fixed64 != nil {
		return *m.Fixed64
	}
	return 0
}

type ProtoTagsSlice struct {
	Sfixed32Slice    []int32  `protobuf:"fixed32,1,rep" json:"Sfixed32Slice,omitempty"`
	Sfixed64Slice    []int64  `protobuf:"fixed64,2,rep" json:"Sfixed64Slice,omitempty"`
	Fixed32Slice     []uint32 `protobuf:"fixed32,3,rep" json:"Fixed32Slice,omitempty"`
	Fixed64Slice     []uint64 `protobuf:"fixed64,4,rep" json:"Fixed64Slice,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoTagsSlice) Reset()         { *m = ProtoTagsSlice{} }
func (m *ProtoTagsSlice) String() string { return proto.CompactTextString(m) }
func (*ProtoTagsSlice) ProtoMessage()    {}

func (m *ProtoTagsSlice) GetSfixed32Slice() []int32 {
	if m != nil {
		return m.Sfixed32Slice
	}
	return nil
}

func (m *ProtoTagsSlice) GetSfixed64Slice() []int64 {
	if m != nil {
		return m.Sfixed64Slice
	}
	return nil
}

func (m *ProtoTagsSlice) GetFixed32Slice() []uint32 {
	if m != nil {
		return m.Fixed32Slice
	}
	return nil
}

func (m *ProtoTagsSlice) GetFixed64Slice() []uint64 {
	if m != nil {
		return m.Fixed64Slice
	}
	return nil
}

func init() {
}
