// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package testproto is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	TestUint
	TestInt
	TestBool
	TestBytes
*/
package testproto

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type TestUint struct {
	Uint8            *uint32 `protobuf:"varint,1,req" json:"Uint8,omitempty"`
	Uint16           *uint32 `protobuf:"varint,2,req" json:"Uint16,omitempty"`
	Uint32           *uint32 `protobuf:"varint,3,req" json:"Uint32,omitempty"`
	Uint64           *uint64 `protobuf:"varint,4,req" json:"Uint64,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TestUint) Reset()         { *m = TestUint{} }
func (m *TestUint) String() string { return proto.CompactTextString(m) }
func (*TestUint) ProtoMessage()    {}

func (m *TestUint) GetUint8() uint32 {
	if m != nil && m.Uint8 != nil {
		return *m.Uint8
	}
	return 0
}

func (m *TestUint) GetUint16() uint32 {
	if m != nil && m.Uint16 != nil {
		return *m.Uint16
	}
	return 0
}

func (m *TestUint) GetUint32() uint32 {
	if m != nil && m.Uint32 != nil {
		return *m.Uint32
	}
	return 0
}

func (m *TestUint) GetUint64() uint64 {
	if m != nil && m.Uint64 != nil {
		return *m.Uint64
	}
	return 0
}

type TestInt struct {
	Int8             *int32 `protobuf:"varint,1,req" json:"Int8,omitempty"`
	Int16            *int32 `protobuf:"varint,2,req" json:"Int16,omitempty"`
	Int32            *int32 `protobuf:"varint,3,req" json:"Int32,omitempty"`
	Int64            *int64 `protobuf:"varint,4,req" json:"Int64,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TestInt) Reset()         { *m = TestInt{} }
func (m *TestInt) String() string { return proto.CompactTextString(m) }
func (*TestInt) ProtoMessage()    {}

func (m *TestInt) GetInt8() int32 {
	if m != nil && m.Int8 != nil {
		return *m.Int8
	}
	return 0
}

func (m *TestInt) GetInt16() int32 {
	if m != nil && m.Int16 != nil {
		return *m.Int16
	}
	return 0
}

func (m *TestInt) GetInt32() int32 {
	if m != nil && m.Int32 != nil {
		return *m.Int32
	}
	return 0
}

func (m *TestInt) GetInt64() int64 {
	if m != nil && m.Int64 != nil {
		return *m.Int64
	}
	return 0
}

type TestBool struct {
	Bool             *bool  `protobuf:"varint,1,req" json:"Bool,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TestBool) Reset()         { *m = TestBool{} }
func (m *TestBool) String() string { return proto.CompactTextString(m) }
func (*TestBool) ProtoMessage()    {}

func (m *TestBool) GetBool() bool {
	if m != nil && m.Bool != nil {
		return *m.Bool
	}
	return false
}

type TestBytes struct {
	String_          *string `protobuf:"bytes,1,req" json:"String,omitempty"`
	Bytes            []byte  `protobuf:"bytes,2,req" json:"Bytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TestBytes) Reset()         { *m = TestBytes{} }
func (m *TestBytes) String() string { return proto.CompactTextString(m) }
func (*TestBytes) ProtoMessage()    {}

func (m *TestBytes) GetString_() string {
	if m != nil && m.String_ != nil {
		return *m.String_
	}
	return ""
}

func (m *TestBytes) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func init() {
}
